package com.example.fuseExample;

import org.apache.activemq.ActiveMQConnectionFactory;
import org.apache.activemq.camel.component.ActiveMQComponent;
import org.apache.camel.LoggingLevel;
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.model.dataformat.CsvDataFormat;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.stereotype.Component;

import javax.jms.ConnectionFactory;

@Component
public class MySpringBootRouter extends RouteBuilder {

    @Autowired
    CvsAggregationStrategy cvsAggregationStrategy;
    @Autowired
    NamesAggregationStrategy namesAggregationStrategy;

    @Bean
    public CsvDataFormat csvDataFormat() {
        return new CsvDataFormat("|");
    }

    @Bean
    public ActiveMQComponent activemq() {
        ConnectionFactory connectionFactory = new ActiveMQConnectionFactory("vm://localhost?broker.persistent=false");
        ActiveMQComponent activemq = new ActiveMQComponent();
        activemq.setConnectionFactory(connectionFactory);
        return activemq;
    }


    @Override
    public void configure() {
        getContext().setAutoStartup(false);

        onException(IllegalArgumentException.class)
                .continued(true) //continues the route
                .log("Rollback local Transaction and continuing with the route")
                .markRollbackOnlyLast() // mark only the last transaction in the route
                .end();

        // testing aggregations with xpath
        from("file:dataIn?noop=true&antInclude=*.xml").routeId("route-XML-files")
                .aggregate(namesAggregationStrategy).xpath("/hello/tag").completionTimeout(10)
                .log("Messages Aggregated XML files: tag: ${headers.tag} = ${body}")
                .to("mock:endRouteXmlFiles");

        //testing aggregations with csv dataformat
        from("file:dataIn?noop=true&antInclude=*.csv").routeId("route-CSV-files")
                .unmarshal("csvDataFormat") //this return a list of list
                .split(body()) //this iterate for each element of list
                .aggregate(cvsAggregationStrategy).simple("${body.get(0)}").completionTimeout(10) //aggregate equal tags
                .log("Messages Aggregated tag CSV files: ${headers.tag} = ${body}")
                .end();

        //testing transactions with database h2 and sql component, creating local boundaries of transactions
        from("timer:hello?repeatCount=1").routeId("routeInvokerTransaction")
                .to("direct:beginTransaction")
                .to("sql:select * from billionaires")
                .log("The result is: ${body}")
                .to("mock:endTransacionalRoute");


        from("direct:beginTransaction").routeId("routeDoTransaction")
                .transacted() //this init a transaction
                .to("sql:update billionaires set career = null")
                .log("Rows updated: ${headers.CamelSqlUpdateCount}")
                .throwException(IllegalArgumentException.class, "error generated by me") //throw exception
                .end();


        //testing JPA and JMS
        from("jpa:com.example.fuseExample.Billionaries?consumeDelete=false&delay=5000").routeId("routeJpa")
                .marshal().jaxb() //convert results from pojos to xml
                .log(LoggingLevel.DEBUG, "the xml of results is ${body}")
                .log("Sending Message")
                .to("activemq:billionariesXml")
                .end();

        //testing JMS
        from("activemq:billionariesXml").routeId("routeJms")
                .log("Received Amq message from temporary broker")
                .log("${body}")
                .end();


    }
}
